// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9A4YI-F2owAmvYBnzK1XxUcut2UZflJo',
    appId: '1:955361731943:web:5051f2ebaed8a79e767bc2',
    messagingSenderId: '955361731943',
    projectId: 'stlist-4402f',
    authDomain: 'stlist-4402f.firebaseapp.com',
    databaseURL: 'https://stlist-4402f.firebaseio.com',
    storageBucket: 'stlist-4402f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV5yPPvUCKGKUThrcwftVVb_u9JER4xvY',
    appId: '1:955361731943:android:22d51f7b19ed18a2767bc2',
    messagingSenderId: '955361731943',
    projectId: 'stlist-4402f',
    databaseURL: 'https://stlist-4402f.firebaseio.com',
    storageBucket: 'stlist-4402f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWu_tS8ixBgORcbdFQCzmvEt9jWMW3Nc',
    appId: '1:955361731943:ios:5b3655ea3e380296767bc2',
    messagingSenderId: '955361731943',
    projectId: 'stlist-4402f',
    databaseURL: 'https://stlist-4402f.firebaseio.com',
    storageBucket: 'stlist-4402f.appspot.com',
    androidClientId: '955361731943-mdtk2qt0043c5sn1q1l25l8s2n0av8dt.apps.googleusercontent.com',
    iosClientId: '955361731943-muogv26h3em6mt0517su0tjglg4lk220.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitpodFlutterQuickstart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzWu_tS8ixBgORcbdFQCzmvEt9jWMW3Nc',
    appId: '1:955361731943:ios:5b3655ea3e380296767bc2',
    messagingSenderId: '955361731943',
    projectId: 'stlist-4402f',
    databaseURL: 'https://stlist-4402f.firebaseio.com',
    storageBucket: 'stlist-4402f.appspot.com',
    androidClientId: '955361731943-mdtk2qt0043c5sn1q1l25l8s2n0av8dt.apps.googleusercontent.com',
    iosClientId: '955361731943-muogv26h3em6mt0517su0tjglg4lk220.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitpodFlutterQuickstart',
  );
}
